name: Scheduled Workflow

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run scheduled task
        run: echo "Scheduled workflow running."
        
