name: Run every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "This workflow runs every 5 minutes"
        
